env:
  TERM: xterm-256color

import:
 - ~/Workspace/alacritty-theme/themes/everforest_dark.yaml

window:
  padding:
    x: 6
    y: 6
  decorations: Buttonless

font:
  normal:
    family: Berkeley Mono
    stype: Regular
  bold:
    family: Berkeley Mono
    stype: Bold
  italic:
    family: Berkeley Mono
    stype: Italic
  bold_italic:
    family: Berkeley Mono
    stype: Bold Italic
  size: 20
  offset:
    x: 0
    y: 1

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"
  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: false

mouse:
  hide_when_typing: true

cursor:
  unfocused_hollow: true

draw_bold_text_with_bright_colors: true

key_bindings:
  - { key: V,      mods: Command, action: Paste            }
  - { key: C,      mods: Command, action: Copy             }
  - { key: Q,      mods: Command, action: Quit             }
  - { key: N,      mods: Command, action: SpawnNewInstance }
  - { key: Return, mods: Command, action: ToggleFullscreen }
  # tmux integration
  - { key: T,         mods: Command, chars: "\x01\x63" }
  - { key: W,         mods: Command, chars: "\x01\x78" }
  - { key: Key1,      mods: Command, chars: "\x01\x31" }
  - { key: Key2,      mods: Command, chars: "\x01\x32" }
  - { key: Key3,      mods: Command, chars: "\x01\x33" }
  - { key: Key4,      mods: Command, chars: "\x01\x34" }
  - { key: Key5,      mods: Command, chars: "\x01\x35" }
  - { key: Key6,      mods: Command, chars: "\x01\x36" }
  - { key: Key7,      mods: Command, chars: "\x01\x37" }
  - { key: Key8,      mods: Command, chars: "\x01\x38" }
  - { key: Key9,      mods: Command, chars: "\x01\x39" }
  - { key: Left,      mods: Command, chars: "\x01\x48" }
  - { key: Down,      mods: Command, chars: "\x01\x4a" }
  - { key: Up,        mods: Command, chars: "\x01\x4b" }
  - { key: Right,     mods: Command, chars: "\x01\x4c" }
  - { key: Minus,     mods: Command, chars: "\x01\x2d" }
  - { key: Backslash, mods: Command, chars: "\x01\x7c" }

